apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
    microservice: customer-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      microservice: customer-service
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongodb
        microservice: customer-service
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
      restartPolicy: Always
      