apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
    microservice: product-service
spec:
  selector:
    app: zookeeper
    microservice: product-service
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: NodePort
  