server:
  port: 8082

spring:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer-groups:
      purchase-group:
        group-id: purchase-mail-group
      registration-group:
        group-id: registration-mail-group
      product-verification-group:
        group-id: product-verification-group

  mail:
    port: 587
    password: "jqmj uaow xcab hdep"
    username: bytemall2024@gmail.com
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

subject:
  purchase: "Thank you for your purchase!"
  registration: "Thank you for your registration!"
  verification: "Lack of products in the storage!"

admins:
  storage-role:
    email: "bytemalloperator4@gmail.com"
  other:
    byte-mall-operator1: "bytemalloperator1@gmail.com"
    byte-mall-operator2: "bytemalloperator2@gmail.com"
    byte-mall-operator3: "bytemalloperator3@gmail.com"


