spring:

  cache:
    type: redis
    redis:
      time-to-live: 600000

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      host: localhost
      port: 27017
      database: customer

server:
  port: 8081