spring:
  datasource:
    password: klochko_08
    username: postgres
    url: jdbc:postgresql://localhost:5432/Customer
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379


  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081