url:
  storageClient: "http://localhost:8084"
  customerClient: "http://localhost:8081"

server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.springframework.kafka.support.serializer.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
