server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:8080
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
