spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Product
    password: klochko_08
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083




