apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql
    microservice: storage-service
spec:
  selector:
    app: postgresql
    microservice: storage-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
  