apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  labels:
    app: postgresql
    microservice: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      microservice: storage-service
  template:
    metadata:
      name: postgresql-pod
      labels:
        app: postgresql
        microservice: storage-service
    spec:
      containers:
        - name: Title
          image: Image
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      