apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
    microservice: purchase-service
spec:
  selector:
    app: kafka
    microservice: purchase-service
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: NodePort
  