spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    consumer-groups:
      order-group:
        group-id: add-order-group
    producer:
      key-serializer: org.springframework.kafka.support.serializer.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  cache:
    type: redis
    redis:
      time-to-live: 600000

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      host: localhost
      port: 27017
      database: customer

url:
  notificationClient: "http://localhost:8082"

server:
  port: 8081