apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
    microservice: customer-service
spec:
  selector:
    app: zookeeper
    microservice: customer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  