apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    microservice: storage-service
spec:
  selector:
    app: redis
    microservice: storage-service
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort
  