apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
    microservice: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      microservice: storage-service
  template:
    metadata:
      name: zookeeper-pod
      labels:
        app: zookeeper
        microservice: storage-service
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      