apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
    microservice: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      microservice: customer-service
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis
        microservice: customer-service
    spec:
      containers:
        - name: Title
          image: Image
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      