apiVersion: v1
kind: Service
metadata:
  name: kafka-Service
  labels:
    app: kafka
    microservice: product-service
spec:
  selector:
    app: kafka
    microservice: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  