apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql
    microservice: product-service
spec:
  selector:
    app: postgresql
    microservice: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  