apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
    microservice: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      microservice: notification-service
  template:
    metadata:
      name: zookeeper-pod
      labels:
        app: zookeeper
        microservice: notification-service
    spec:
      containers:
        - name: Title
          image: Image
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      