spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.type: com.shop.storageservice.DTO.OrderDuplicateDTO
    consumer-groups:
      order-group:
        group-id: storage-after-purchase-reduce-group


  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    password: klochko_08
    username: postgres
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
    redis:
      time-to-live: 600000


  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8084

url:
  productClient: "http://localhost:8083"
  customerClient: "http://localhost:8081"