spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Storage
    password: klochko_08
    username: Storage
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
