apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
    microservice: notification-service
spec:
  selector:
    app: kafka
    microservice: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  