apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
    microservice: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      microservice: notification-service
  template:
    metadata:
      name: kafka-pod
      labels:
        app: kafka
        microservice: notification-service
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      