apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
    microservice: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      microservice: notification-service
  template:
    metadata:
      name: kafka-pod
      labels:
        app: kafka
        microservice: notification-service
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      