apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
    microservice: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      microservice: storage-service
  template:
    metadata:
      name: kafka-pod
      labels:
        app: kafka
        microservice: storage-service
    spec:
      containers:
        - name: Title
          image: Image
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      